# .swiftlint.yml
disabled_rules: # rule identifiers to exclude from running
  - line_length # Disable line length rule

opt_in_rules: # some rules are only opt-in
  - empty_count # Count empty lines

# Basic rules
line_length:
  warning: 120 # Warn if a line exceeds 120 characters
  error: 150 # Error if a line exceeds 150 characters

type_body_length:
  warning: 200 # Warn if a type body exceeds 200 lines
  error: 300 # Error if a type body exceeds 300 lines

function_body_length:
  warning: 40 # Warn if a function body exceeds 40 lines
  error: 50 # Error if a function body exceeds 50 lines

identifier_name:
  min_length: 3 # Minimum length for identifiers
  max_length: 30 # Maximum length for identifiers
  allowed_symbols: ["_"] # Allow underscores in identifiers

# Other rules can be added as needed
